unique_ids:
  assets:
    standard-page.html: BWE63G74G7562ZCKLOHCFDW2GN4FFHTW
    theme.css: OKYNSMTJWD343TLEJJXAY47JWXY7RG67
  forms: {}
  modules: {}
  scripts: {}
  server_modules:
    ServerModule1: '1752862300598779812753968.7992'
